### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by monkeyjp** [4GeeksAcademy/fs-pt-92-Instagram-bootstrap-feed-Gonzalo#1]
Esta bastante bien, sin embargo a nivel responsivo tienes unos detalles a mejorar. 
Fijate como se ve el navbar o la vista de columna cuando estamos en una pantalla pequeña. O lo pequeñas que se ven las imagenes del grid. 
![Screenshot 2024-11-18 at 10 19 40](https://github.com/user-attachments/assets/bc2998fa-0be3-4e6d-9270-990446c82695)
![Screenshot 2024-11-18 at 10 19 27](https://github.com/user-attachments/assets/9ef430f7-fb1c-4875-95e5-2ed5efe30f64)
Fijate que haciendo una pequeña modificacion en el codigo como esta: 
![Screenshot 2024-11-18 at 10 27 07](https://github.com/user-attachments/assets/3ff2a8e6-b5ca-45dd-8fba-308e21ffb244)
esto hara que en pantallas moviles tu aplicacion se vea asi.
![Screenshot 2024-11-18 at 10 28 03](https://github.com/user-attachments/assets/ee6a768e-5f91-4f18-ab92-73eda94b2087)

**Comment by Goblanch** [comment]
Listo. He añadido un toggler en el navbar para cuando la pantalla sea muy pequeña lo sustituya. También he cambiado los dos tipos de visualización para que se adapten en tamaño según la pantalla como me comentaste.
